# Generated by Django 6.0.3 on 2026-03-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_usersfavouritecocktails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingrediets',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cocktails.ingredient'),
        ),
    ]
