# Generated by Django 6.0.3 on 2026-03-23 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_alter_cocktailingrediets_ingredient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocktails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersfavouritecocktails',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cocktails.cocktail'),
        ),
        migrations.AlterField(
            model_name='usersfavouritecocktails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CocktailIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='ml', max_length=10)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='cocktails.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cocktails.ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(related_name='used_in', through='cocktails.CocktailIngredients', to='cocktails.ingredient'),
        ),
        migrations.DeleteModel(
            name='CocktailIngrediets',
        ),
    ]
